import Head from 'next/head';
import type { AppProps } from 'next/app';
import { GlobalStyle } from '@src/styles/global-styles';
import Layout from '@src/components/layout/Layout';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Shape Games Web Test</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <GlobalStyle />
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
